// Generated by CoffeeScript 1.9.2
(function() {
  myAppControllers.controller('HController', [
    '$scope', '$log', function($scope, $log) {
      var mockDataTpl;
      $scope.tabConfig = {
        titleList: ['title1', 'title2', 'title3']
      };
      mockDataTpl = {
        'list|20': [
          {
            'title': '@STRING'
          }
        ]
      };
      $scope.list = Mock.mock(mockDataTpl).list;
      $scope.$on('tabClickEvent', function(e, data) {
        var index;
        index = data.index;
        switch (index) {
          case 0:
            mockDataTpl = {
              'list|20': [
                {
                  'title': '@STRING'
                }
              ]
            };
            break;
          case 1:
            mockDataTpl = {
              'list|10': [
                {
                  'title': '@STRING'
                }
              ]
            };
            break;
          case 2:
            mockDataTpl = {
              'list|15': [
                {
                  'title': '@STRING'
                }
              ]
            };
            break;
          default:
            break;
        }
        $scope.list = Mock.mock(mockDataTpl).list;
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=controller.js.map
