// Generated by CoffeeScript 1.9.2
(function() {
  myAppDirectives.directive('tab', [
    '$log', function($log) {
      return {
        restrict: 'EA',
        transclude: true,
        replace: true,
        scope: {
          tabConfig: '='
        },
        template: '<div class="g-tab-ctn">\n    <div class="g-tab-tt">\n        <div class="m-tab-tt" ng-repeat="tabTitleObj in tabTitleList" style="width: {{100 / tabNum}}%">\n            <button ng-class="{selected: activeTab === tabTitleObj.index}" ng-click="tabTitleClickHandler(tabTitleObj)">\n                <i>{{tabTitleObj.title}}</i>\n            </button>\n        </div>\n    </div>\n    <div class="g-tab-content-ctn" ng-transclude>\n\n    </div>\n</div>',
        link: function(scope, element, attrs) {
          var elem, i, j, len, tabConfig, tabTitleList;
          tabConfig = scope.tabConfig;
          tabTitleList = tabConfig.titleList;
          scope.tabNum = tabTitleList.length;
          scope.activeTab = 0;
          scope.tabTitleList = [];
          for (i = j = 0, len = tabTitleList.length; j < len; i = ++j) {
            elem = tabTitleList[i];
            scope.tabTitleList.push({
              index: i,
              title: elem
            });
          }
          scope.tabTitleClickHandler = function(tabTitleObj) {
            scope.activeTab = tabTitleObj.index;
            scope.$emit('tabClickEvent', {
              index: tabTitleObj.index
            });
          };
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=directive.js.map
