// Generated by CoffeeScript 1.9.2
(function() {
  myAppDirectives.directive('footer', [
    '$log', 'dataCache', function($log, dataCache) {
      return {
        restrict: 'A',
        replace: true,
        transclude: true,
        templateUrl: './templates/directive/footer.tpl.html',
        scope: {
          config: '='
        },
        link: function(scope, element, attrs) {
          var btnObj, condition, config, guid, i, j, k, l, leftItemObj, len, len1, len2, m, n, ref, ref1, ref2, ref3, ref4;
          config = scope.config;
          scope.btnList = config.btnList;
          scope.btnNum = scope.btnList.length;
          scope.active = 0;
          scope.isMaskShow = false;
          scope.contentType = '';
          guid = '';
          ref = scope.btnList;
          for (i = l = 0, len = ref.length; l < len; i = ++l) {
            btnObj = ref[i];
            btnObj.active = i;
            btnObj.guid = (ref1 = Mock.Random.guid()) != null ? ref1 : new Date().getTime();
            if (btnObj.type === 'double') {
              ref2 = btnObj.content.list;
              for (j = m = 0, len1 = ref2.length; m < len1; j = ++m) {
                leftItemObj = ref2[j];
                leftItemObj.guid = (ref3 = Mock.Random.guid()) != null ? ref3 : new Date().getTime();
                if (angular.isArray(leftItemObj.condition)) {
                  ref4 = leftItemObj.condition;
                  for (k = n = 0, len2 = ref4.length; n < len2; k = ++n) {
                    condition = ref4[k];
                    condition.active = k;
                  }
                }
              }
            }
          }
          scope.btnClickEventHandler = function(btnObj) {
            var contentObj, doubleItem, len3, o, ref5;
            scope.contentType = btnObj.type;
            guid = btnObj.guid;
            switch (scope.contentType) {
              case 'single':
                scope.singleItemActive = dataCache.get('singleItemActive' + guid) || 0;
                scope.contents = btnObj.content;
                break;
              case 'double':
                doubleItem = dataCache.get('doubleItem' + guid);
                if (doubleItem != null) {
                  scope.doubleItemActive = doubleItem.doubleLeftItem.active;
                  scope.conditionItemActive = doubleItem.conditionItemActive;
                } else {
                  scope.doubleItemActive = 0;
                  scope.conditionItemActive = 0;
                }
                scope.contents = btnObj.content.list;
                break;
              default:
                break;
            }
            ref5 = scope.contents;
            for (i = o = 0, len3 = ref5.length; o < len3; i = ++o) {
              contentObj = ref5[i];
              contentObj.active = i;
            }
            if (scope.active === btnObj.active) {
              scope.isMaskShow = !scope.isMaskShow;
            } else {
              scope.isMaskShow = true;
            }
            scope.active = btnObj.active;
          };
          scope.maskClickEventHandler = function() {
            scope.isMaskShow = false;
          };
          scope.singleTypeClickEventHandler = function(contentObj, e) {
            e.stopPropagation();
            scope.singleItemActive = contentObj.active;
            dataCache.put('singleItemActive' + guid, contentObj.active);
            scope.$emit('singleTypeSelectEvent', contentObj);
          };
          scope.doubleTypeLeftListClickEventHandler = function(contentObj, e) {
            e.stopPropagation();
            scope.doubleItemActive = contentObj.active;
            dataCache.put('doubleLeftItem' + contentObj.guid, contentObj);
            scope.conditionItemActive = dataCache.get('conditionItemActive' + contentObj.guid) || 0;
            scope.$emit('doubleTypeSelectEvent', contentObj);
          };
          scope.doubleTypeRightListClickEventHandler = function(contentObj, condition, e) {
            e.stopPropagation();
            scope.conditionItemActive = condition.active;
            dataCache.put('conditionItemActive' + contentObj.guid, condition.active);
            dataCache.put('doubleItem' + guid, {
              doubleLeftItem: contentObj,
              conditionItemActive: condition.active
            });
          };
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=directive.js.map
